chop/api/urls.py
from rest_framework import routers
from django.urls import path, include, re_path

from .views import ArticleAll, NewProduct
from .viewsets import ArticleViewSet, FeedbackViewSet, BrandViewSet, ProductViewSet, AnimalCategoryViewSet, \
    ProductCategoryViewSet
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

router = routers.DefaultRouter()
router.register(r'article', ArticleViewSet, basename='article')
router.register(r'feedback', FeedbackViewSet, basename='feedback')
router.register(r'brand', BrandViewSet, basename='brand')
router.register(r'product', ProductViewSet, basename='product')
router.register(r'animal_category', AnimalCategoryViewSet, basename='animal_category')
router.register(r'product_category', ProductCategoryViewSet, basename='product_category')


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [

    path('', include(router.urls)),
    # re_path(r'^swagger(?P\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # path('feedback/', FeedbackViewSet.as_view({'get': 'list', 'post': 'create'})),
    # path('feedback/<int:pk>/', FeedbackViewSet.as_view({'get': 'retrieve'})),
    path('article_all/', ArticleAll.as_view()),
    path('new_product/', NewProduct.as_view())

]

chop/catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'catalog'

urlpatterns = [

    path('', index, name='index'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    path('accounts/logout/', UserLogoutView.as_view(), name='logout'),

]

chop/chop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('api/', include('api.urls')),

]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chop/catalog/models.py
import requests
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from datetime import datetime
from os.path import splitext

class AdvUser(AbstractUser):
    tel = models.CharField(max_length=13)

    class Meta(AbstractUser.Meta):
        pass

def get_user_id(request):
    return request.user

def get_timestamp_path(instance, filename):
    return '%s%s' % (datetime.now().timestamp(), splitext(filename)[1])

# Категории животных
class AnimalCategory(models.Model):
    name = models.CharField(max_length=50, verbose_name='Категория животных')
    image = models.ImageField(blank=True, null=True, upload_to=get_timestamp_path, verbose_name='Изображение')
    slug = models.SlugField(null=False, blank=True, db_index=True, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('animal_category', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

# Категории товара
class ProductCategory(models.Model):
    MEASURE = (
        ('кг.', 'кг.'),
        ('л.', 'л.'),
        ('шт.', 'шт.'),
        ('гр.', 'гр.'),
    )
    name = models.CharField(max_length=50, verbose_name='Категория товара')
    measure = models.CharField(max_length=20,choices=MEASURE)

    def __str__(self):
        return self.name

#Брэнд
class Brand(models.Model):
    name = models.CharField(max_length=50, verbose_name='Брэнд')
    image = models.ImageField(blank=True, null=True, upload_to=get_timestamp_path, verbose_name='Логотип')


    def __str__(self):
        return self.name

#Товар
class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название товара')
    author = models.ForeignKey(AdvUser, on_delete=models.CASCADE, verbose_name='Автор')
    animalcategory = models.ManyToManyField(AnimalCategory, verbose_name='Категория животных', related_name='product')
    productcategory = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='Категория продукта')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, verbose_name='Брэнд')
    discription = models.TextField()
    image = models.ImageField(blank=True, null=True, upload_to=get_timestamp_path, verbose_name='Изображение')
    price = models.IntegerField(verbose_name='Стоимость')
    count = models.IntegerField(verbose_name='В наличии')
    first_offer = models.IntegerField(verbose_name='Первое предложение кол-ва', default=1)
    second_offer = models.IntegerField(verbose_name='Второе предложение кол-ва', default=1)
    views = models.IntegerField(verbose_name="Просмотры", default=0)

    def __str__(self):
        return self.name
    class Meta:
        ordering = ['-id']

class Feedback(models.Model):
    name = models.CharField(max_length=10, verbose_name='Имя')
    content = models.TextField(verbose_name='Контент')
    phone_regex = RegexValidator(regex=r'^\+375\d{9,9}$',
                                 message="Введите номер в формате +3753363785379")
    tel = models.CharField(max_length=14, verbose_name='Телефон', validators=[phone_regex])
    petName = models.CharField(max_length=50, verbose_name='Имя питомца')

    def __str__(self):
        return self.name

class Article(models.Model):
    image = models.ImageField(blank=True, null=True, upload_to=get_timestamp_path, verbose_name='Изображение')
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Контент')
    time_of_read = models.IntegerField(verbose_name='Время чтения в минутах')
    created_at = models.DateField(auto_now_add=True, blank=True, null=True)
    owner = models.CharField(max_length=50, default=1, blank=True, null=True)

    # def save(self, user_id):
    #     if not self.owner:
    #         self.owner = user_id
    #     return super().save()


    def __str__(self):
        return self.title





# Create your models here.

chop/catalog/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .models import *


class CatAnimal(forms.ModelForm):

    model = AnimalCategory
    fields = ('name')
    widgets = {'slug': forms.HiddenInput}






class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Электронная почта', initial='')
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль(повторно)', widget=forms.PasswordInput,
                                help_text='Подтвердите введенный ранее пароль')

    def clean_password1(self):
        password = self.cleaned_data['password']
        if password:
            password_validation.validate_password(password)
        return password

    def clean(self):
        super().clean()
        password = self.cleaned_data['password']
        password2 = self.cleaned_data['password2']
        if password and password2 and password != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.is_active = False
        if commit:
            user.save()
        return user

    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'input'

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password', 'password2')

chop/catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import Count, Avg
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import RegisterUserForm
from .models import *

def index(request):
    category = AnimalCategory.objects.all()
    products = Product.objects.all()[:4]
    brands = Brand.objects.all()[:5]
    feedback = Feedback.objects.all()[:1]
    articles = Article.objects.all()[:3]
    context = {
        'category': category,
        'products': products,
        'brands': brands,
        'feedback': feedback,
        'articles': articles,
    }
    # brand = Brand.objects.all().order_by('product_set')
    #
    #
    # # print(brand.product_set.count())
    # print(brand)
    brand = Brand.objects.annotate(Count('product')).order_by('-product__count')[:2]
    prices = Brand.objects.annotate(Count('product__price'))
    for price in prices:
        print(price.product__price__count)
        print(price)
        # print(dir(price))


    return render(request, 'index.html', context)


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('catalog:index')

class UserLoginView(LoginView):
    template_name = 'login.html'
    success_url = reverse_lazy('catalog:index')

class UserLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'logout.html'
# Create your views here.

chop/catalog/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Територия ZOO{% endblock %}</title>
    <link rel="icon" href="static/img/favicon.ico">
    <link rel="stylesheet" type="text/css"
    href="{% static 'css/index.css' %}">
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=API_KEY" type="text/javascript"></script>
</head>
<body>
<header>
    <div class="first-header">
        <div class="adress_1"><img class="nav_icon1" src="{% static 'img/1.svg' %}" alt="">
            <p>Минск, ул. Чюрлёниса, 6.</p></div>
        <div class="adress_1"><img class="nav_icon2" src="{% static 'img/2.svg' %}" alt="">
            <p>Пон.-Пят. 10:00-21:00 | Суб.-Вос. 10:00-20:00</p></div>
        <div class="adress_2"><img class="nav_icon2" src="{% static 'img/3.svg' %}" alt="">
            <strong>+ 375 (44) 501 03 55</strong><a href="#" class="a_icon_hed1"><img class="nav_icon2" src="{% static 'img/4.svg' %}" alt=""></a></div>
        <div class="adress_1"><a class="a_hed1" href="#">Обратный звонок</a></div>

    </div>
    <div class="second-header">
        <div class="adress_1"><img class="logo" src="{% static 'img/logo.jpg' %}" alt="">
        </div>
        <div class="input_header"><input class="input_h" placeholder="Поиск" type="text" value=""></div>
        <div class="adress_1"><a class="a_hed2" href="/">Главная</a></div>
        <div class="adress_1"><a class="a_hed2"  onClick="get_all_product(event)" href="#catalog">Каталог</a></div>
        <div class="adress_1"><a class="a_hed2" href="#">Акции</a></div>
        <div class="adress_1"><a class="a_hed2" href="#">Статьи</a></div>
        <div class="adress_1"><a class="a_hed2" href="{% url 'catalog:register' %}">Регистрация</a></div>
        <div class="adress_1"><a class="a_hed2" href="{% url 'catalog:login' %}">Вход</a></div>
        {% if user.is_authenticated  %}
        <div class="adress_1"><a class="a_hed2" href="{% url 'catalog:logout' %}">Выход</a></div>
        {% endif %}
        <div class="adress_1"><div class="korz"><a href="#" class="a_icon_hed1"><img class="nav_icon3" src="{% static 'img/1.jpg' %}" alt=""></a>
            <p>1</p></div></div>
    </div>

</header>

<div class="content" id="content">{% block content %}

    <div id="category_animal"></div>

    <div id="all_need"></div>

    <div id="all_product"></div>

    <div id="akcii" class="all_product"></div>


    <div id="new_product"></div>


    <div id="brand"></div>

    <div class="feedbacks" id="feedback"></div>

    <div id="articles"></div>

    <div class="all_need">
        <div class="last0">
            <div>
                <h1 class="h1_1">Здравствуйте, счастливый хозяин любимого питомца!</h1>
                <p>Меня зовут Ирина, 2 года назад моя бесконечная любовь к животным трансформировалась в магазин
                    «Территория ZOO». Место, главная цель которого — забота о полноценной жизни питомцев, здоровой,
                    долгой, радостной и гармоничной. Наш долг — создавать лучшее предложение для ваших домашних любимцев.</p>
            </div>
            <div class="all_need1">
                <div class="last1"></div>
                <div class="all_need3"><strong>За 7 минут соберем заказ</strong> <br> Выбирайте товары на сайте, забирайте в удобное время в нашем
                    магазине. Уже через 30 минут собранный и упакованный заказ будет ждать вас.</div></div>
            <div class="all_need1">
                <div class="last2"></div>
                <div class="all_need3"><strong>Поможем с выбором товаров</strong> <br> Задавайте вопросы профессионалам, получайте консультации по кормлению и содержанию питомца.</div></div>
            <div class="all_need1">
                <div class="last3"></div>
                <div class="all_need3"><strong>Поставим товар на заказ!</strong> <br> Мы работаем с лучшими поставщиками сертифитированного товара для животных. Если нужного Вам товара не будет
                    в наличии мы в кратчайшие сроки договоримся о его поставке и сообщим Вам.</div>
            </div>

        </div>
        <div>
            <img class="" src="{% static 'img/8.jpg' %}" alt="">
        </div>
    {% endblock %}</div>



{% block info %}
<div class="info">
    <div id="map"></div>
    <div class="info_again">
        <div class="info_free"><h2>Бесплатно проконсультируем по любому вопросу связанному с вашим любимцем</h2></div>
        <div class="info_else"><strong>Адрес:</strong>
            <p><img class="nav_icon1" src="{% static 'img/1.svg' %}" alt="">Минск, ул. Чюрлёниса, 6.</p>
            </div>
        <div class="info_else"><strong>Время работы:</strong>
            <p><img class="nav_icon2" src="{% static 'img/2.svg' %}" alt="">
            Пон.-Пят. 10:00-21:00 | Суб.-Вос. 10:00-20:00</p></div>
        <div class="info_else"><p><strong>Телефон:</strong></p><img class="nav_icon2" src="{% static 'img/3.svg' %}" alt="">
            <strong>+ 375 (44) 501 03 55</strong><br></div>
        <div class="info_else"><p></p><strong>Пишите нам в социальных сетях:</strong>
        <p><a href="#" class=""><img class="" src="{% static 'img/4.svg' %}" alt=""></a></p></div>
        </div>

    </div>

</div>

<div id="article_detail">

</div>
<div id="push">

</div>{% endblock %}

<footer>
    <div class="foot1">
        <div class="adress_1"><img class="logo2" src="{% static 'img/logo2.jpg' %}" alt=""></div>
        <div class="foot">
            <div class="adress_1"><a class="a_foot1" href="/">Главная</a></div>
            <div class="adress_1"><a class="a_foot1" onClick="get_all_product(event)">Каталог</a></div>
            <div class="adress_1"><a class="a_foot1" href="#">Акции</a></div>
            <div class="adress_1"><a class="a_foot1" href="#">Статьи</a></div>
            <div class="adress_1"><a class="a_foot1" href="{% url 'catalog:register' %}">Регистрация</a></div>
            <div class="adress_1"><a class="a_hed2" href="{% url 'catalog:login' %}">Вход</a></div>
            {% if user.is_authenticated  %}
            <div class="adress_1"><a class="a_hed2" href="{% url 'catalog:logout' %}">Выход</a></div>
            {% endif %}
        </div>


    </div>
    <div class="foot2"></div>


    <div class="foot3">
        <div class="adress_1"><img class="nav_icon1" src="{% static 'img/1.svg' %}" alt="">
            <p>Минск, ул. Чюрлёниса, 6.</p></div>
        <div class="adress_1"><img class="nav_icon2" src="{% static 'img/2.svg' %}" alt="">
            <p>Пон.-Пят. 10:00-21:00 | Суб.-Вос. 10:00-20:00</p></div>
        <div class="adress_2"><img class="nav_icon2" src="{% static 'img/3.svg' %}" alt="">
            <strong>+ 375 (44) 501 03 55</strong><a href="#" class="a_icon_hed1"><img class="nav_icon2" src="{% static 'img/4.svg' %}" alt=""></a></div>
        <div class="adress_1"><a class="a_hed1" href="#">Обратный звонок</a></div>

    </div>



</footer>
<script type="text/javascript">

	ymaps.ready(init);
	var myMap;

	function init() {

		myMap = new ymaps.Map("map", {
			center: [53.85440831689402,27.478958650272087], // Координаты центра карты
			zoom: 16 // Маштаб карты
		});

		myMap.controls.add(
			new ymaps.control.ZoomControl()  // Добавление элемента управления картой
		);

		myPlacemark = new ymaps.Placemark([53.85440831689402,27.478958650272087], { // Координаты метки объекта
			balloonContent: "<div class='ya_map'>Территория ZOO!</div>" // Подсказка метки
		}, {
			preset: "twirl#redDotIcon" // Тип метки
		});

		myMap.geoObjects.add(myPlacemark); // Добавление метки
		myPlacemark.balloon.open(); // Открытие подсказки метки

	};

</script>
<script src="{% static 'js/article.js' %}"></script>
<script src="{% static 'js/feedback.js' %}"></script>
<script src="{% static 'js/brand.js' %}"></script>
<script src="{% static 'js/new_product.js' %}"></script>
<script src="{% static 'js/akcii.js' %}"></script>
<script src="{% static 'js/all_product.js' %}"></script>
<script src="{% static 'js/get_all_product.js' %}"></script>
<script src="{% static 'js/all_need.js' %}"></script>
<script src="{% static 'js/category_animal.js' %}"></script>
<script src="{% static 'js/get_product_div.js' %}"></script>
<script src="{% static 'js/product_detail.js' %}"></script>

</body>
</html>

chop/catalog/templates/login.html
{% extends "index.html" %}
{% load static %}
{% block title %}

Вход на сайт
{% endblock %}
{% block content %}


<div class="create_user">
    <div class="gen">
        <h1>Вход</h1>

{% if user.is_authenticated %}
<p>Вы уже выполнили вход</p>
{% else %}
<div><form action="" method="POST">
    {% csrf_token %}
    <p> {{ form.username.label_tag }} {{ form.username  }} </p>
            <p class="form_error">{{ form.username.errors.as_text }}</p>
            <p> {{ form.email.label_tag }} {{ form.email  }} &#160; {{ form.email.help_text }} </p>
            <p class="form_error">{{ form.email.errors }}</p>
            <p> {{ form.password.label_tag }} {{ form.password  }} </p>
            <p class="form_error">{{ form.password.errors.as_text }}</p>
                <button class="myButton_reg">Вход</button>
                <input type="reset" class="myButton_reg">
</form></div>
{% endif %}
        </div></div>
{% endblock %}
{% block info %}
{% endblock %}

chop/catalog/templates/logout.html
{% extends "index.html" %}
{% block title %}
ВЫход
{% endblock %}
{% block content %}
<div class="create_user">
    <div class="gen">
        <h1>Выход</h1>
        <div>
         <p>Вы успешно вышли с сайта</p>
            </div></div></div>
{% endblock %}
{% block info %}
{% endblock %}

chop/catalog/templates/register.html
{% extends "index.html" %}
{% load static %}
{% block title %}
 Регистрация
{% endblock %}
{% block content %}

<div class="create_user">
    <div class="gen">
        <h1>Регистрация нового пользователя:</h1>
        <div>
            <form id="reg_form" method="POST" action="">
                {% csrf_token %}
            <p> {{ form.username.label_tag }} {{ form.username  }} </p>
            <p class="form_error">{{ form.username.errors.as_text }}</p>
            <p> {{ form.email.label_tag }} {{ form.email  }} &#160; {{ form.email.help_text }} </p>
            <p class="form_error">{{ form.email.errors }}</p>
            <p> {{ form.password.label_tag }} {{ form.password  }} </p>
            <p class="form_error">{{ form.password.errors.as_text }}</p>
            <p> {{ form.password2.label_tag }} {{ form.password2  }} &#160; {{ form.password2.help_text }} </p>
            <p class="form_error">{{ form.password2.errors.as_text }}</p>
                <button class="myButton_reg">Регистрация</button>
                <input type="reset" class="myButton_reg">
            </form>
            </div></div></div>
{% endblock %}
{% block info %}
{% endblock %}